# Generated by Django 4.2.11 on 2026-05-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='branch_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='micr_code',
        ),
    ]
