# Generated by Django 4.2.11 on 2026-05-22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_bank_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='profiles/',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['jpg', 'jpeg', 'png'],
                    ),
                ],
            ),
        ),
    ]
