# Generated by Django 4.2.11 on 2026-03-17 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_payslip_basic_salary_remove_payslip_hra_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";',
                'ALTER TABLE core_wikipage DROP CONSTRAINT IF EXISTS core_wikipage_category_id_e2895e8d_fk_core_wikicategory_id;',
                'ALTER TABLE core_adminnotification ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE core_adminnotification ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE core_adminnotification ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE core_adminnotification ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE core_document ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE core_document ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE core_document ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE core_document ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE core_payslip ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE core_payslip ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE core_payslip ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE core_payslip ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE core_profile ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE core_profile ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE core_profile ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE core_profile ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE core_usernotification ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE core_usernotification ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE core_usernotification ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE core_usernotification ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE core_wikicategory ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE core_wikicategory ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE core_wikicategory ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE core_wikicategory ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE core_wikipage ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE core_wikipage ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE core_wikipage ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE core_wikipage ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE core_wikipage ALTER COLUMN category_id TYPE uuid USING NULL::uuid;',
                'ALTER TABLE core_wikipage ADD CONSTRAINT core_wikipage_category_id_e2895e8d_fk_core_wikicategory_id FOREIGN KEY (category_id) REFERENCES core_wikicategory(id) DEFERRABLE INITIALLY DEFERRED;',
            ],
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='adminnotification',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='document',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='payslip',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='profile',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='usernotification',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='wikicategory',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='wikipage',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
