SecretProviderClass:
- name: youpayroll-aps-envs
  namespace: youpayroll-aps
  provider: vault
  parameters:
    roleName: "ygag-eks-v2-youpayroll-aps-app-role"
    objects: |
      - objectName: "application.env"
        secretPath: "ygag-secrets/data/it/sandbox/youpayroll/env"
        secretKey: "app-env"
      - objectName: "application-devops.env"
        secretPath: "ygag-secrets/data/devops/sandbox/external/it/youpayroll/env"
        secretKey: "app-env"
