# Generated by Django 4.2.11 on 2026-03-17 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zohopeople', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";',
                'ALTER TABLE zohopeople_zohopeopleformtoken ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE zohopeople_zohopeopleformtoken ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE zohopeople_zohopeopleformtoken ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE zohopeople_zohopeopleformtoken ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
            ],
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='zohopeopleformtoken',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
