# Generated by Django 4.2.11 on 2026-05-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohopeople', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohopeopleformtoken',
            name='last_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
