# Generated by Django 4.2.11 on 2026-05-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohopeople', '0002_zohopeopleformtoken_zoho_people_form_token_singleton'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zohopeopleformtoken',
            options={},
        ),
    ]
