# Generated by Django 4.2.11 on 2026-05-22 04:37
#
# This intentionally records the removal of the token model's default
# ordering. ZohoPeopleFormToken is a singleton, and callers should address it
# by pk rather than depend on implicit ordering.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohopeople', '0002_zohopeopleformtoken_zoho_people_form_token_singleton'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zohopeopleformtoken',
            options={},
        ),
    ]
