# Generated by Django 4.2.11 on 2026-03-17 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0005_alter_payee_pan_no'),
        ('payroll', '0007_remove_payment_uuid_remove_payrun_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='payee',
            name='uuid',
        ),
        migrations.RunSQL(
            sql=[
                'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";',
                'DO $$\n'
                'DECLARE r record;\n'
                'BEGIN\n'
                '  FOR r IN\n'
                '    SELECT conname FROM pg_constraint\n'
                '    WHERE contype = \'f\' AND conrelid = \'payees_bankdetails\'::regclass\n'
                '  LOOP\n'
                '    EXECUTE format(\'ALTER TABLE payees_bankdetails DROP CONSTRAINT %I\', r.conname);\n'
                '  END LOOP;\n'
                '  FOR r IN\n'
                '    SELECT conname FROM pg_constraint\n'
                '    WHERE contype = \'f\' AND conrelid = \'payees_bankdetailsack\'::regclass\n'
                '  LOOP\n'
                '    EXECUTE format(\'ALTER TABLE payees_bankdetailsack DROP CONSTRAINT %I\', r.conname);\n'
                '  END LOOP;\n'
                'END $$;',
                'ALTER TABLE payees_payee ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE payees_payee ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE payees_payee ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE payees_payee ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE payees_bankdetails ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE payees_bankdetails ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE payees_bankdetails ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE payees_bankdetails ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE payees_bankdetailsack ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE payees_bankdetailsack ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE payees_bankdetailsack ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE payees_bankdetailsack ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE payees_bankdetails ALTER COLUMN payee_id TYPE uuid USING NULL::uuid;',
                'ALTER TABLE payees_bankdetailsack ALTER COLUMN payee_id TYPE uuid USING NULL::uuid;',
                'ALTER TABLE payees_bankdetails ADD CONSTRAINT payees_bankdetails_payee_id_fk FOREIGN KEY (payee_id) REFERENCES payees_payee(id) DEFERRABLE INITIALLY DEFERRED;',
                'ALTER TABLE payees_bankdetailsack ADD CONSTRAINT payees_bankdetailsack_payee_id_fk FOREIGN KEY (payee_id) REFERENCES payees_payee(id) DEFERRABLE INITIALLY DEFERRED;',
            ],
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='bankdetails',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='bankdetailsack',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='payee',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
