# Generated by Codex on 2026-05-22

from django.db import migrations, models
import django.db.models.deletion


def backfill_or_remove_legacy_null_acknowledgements(apps, schema_editor):
    BankDetails = apps.get_model('payees', 'BankDetails')
    BankDetailsAck = apps.get_model('payees', 'BankDetailsAck')

    payee_ids = (
        BankDetailsAck.objects
        .filter(bank_details__isnull=True)
        .values_list('payee_id', flat=True)
        .distinct()
    )

    for payee_id in payee_ids:
        bank_details_ids = list(
            BankDetails.objects
            .filter(payee_id=payee_id)
            .order_by('id')
            .values_list('id', flat=True)
        )
        null_ack_ids = list(
            BankDetailsAck.objects
            .filter(payee_id=payee_id, bank_details__isnull=True)
            .order_by('uploaded_date', 'id')
            .values_list('id', flat=True)
        )

        if not bank_details_ids:
            BankDetailsAck.objects.filter(id__in=null_ack_ids).delete()
            continue

        acknowledged_bank_details_ids = set(
            BankDetailsAck.objects
            .filter(bank_details_id__in=bank_details_ids)
            .exclude(bank_details__isnull=True)
            .values_list('bank_details_id', flat=True)
        )
        unacknowledged_bank_details_ids = [
            bank_details_id
            for bank_details_id in bank_details_ids
            if bank_details_id not in acknowledged_bank_details_ids
        ]

        if not unacknowledged_bank_details_ids:
            BankDetailsAck.objects.filter(id__in=null_ack_ids).delete()
            continue

        bank_details_id = unacknowledged_bank_details_ids[0]
        BankDetailsAck.objects.filter(id=null_ack_ids[0]).update(bank_details_id=bank_details_id)
        if len(null_ack_ids) > 1:
            BankDetailsAck.objects.filter(id__in=null_ack_ids[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0005_bankdetailsack_unique_ack_per_bank_details'),
    ]

    operations = [
        migrations.RunPython(
            backfill_or_remove_legacy_null_acknowledgements,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='bankdetailsack',
            name='unique_ack_per_bank_details',
        ),
        migrations.AlterField(
            model_name='bankdetailsack',
            name='bank_details',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='acknowledgements',
                to='payees.bankdetails',
            ),
        ),
        migrations.AddConstraint(
            model_name='bankdetailsack',
            constraint=models.UniqueConstraint(
                fields=('bank_details',),
                name='unique_ack_per_bank_details',
            ),
        ),
    ]
