# Generated by Codex on 2026-05-25

from django.db import migrations, models
from django.db.models import Count


def collapse_duplicate_bank_details(apps, schema_editor):
    BankDetails = apps.get_model('payees', 'BankDetails')

    duplicate_payee_ids = (
        BankDetails.objects
        .values('payee_id')
        .annotate(bank_details_count=Count('id'))
        .filter(bank_details_count__gt=1)
        .values_list('payee_id', flat=True)
    )

    for payee_id in duplicate_payee_ids:
        bank_detail_ids = list(
            BankDetails.objects
            .filter(payee_id=payee_id)
            .order_by('-id')
            .values_list('id', flat=True)
        )
        BankDetails.objects.filter(id__in=bank_detail_ids[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0006_bankdetailsack_require_bank_details'),
    ]

    operations = [
        migrations.RunPython(
            collapse_duplicate_bank_details,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='bankdetails',
            constraint=models.UniqueConstraint(
                fields=('payee',),
                name='unique_bank_details_per_payee',
            ),
        ),
    ]
