# Generated by Django 4.2.11 on 2026-03-17 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_component'),
        ('payroll', '0007_remove_payment_uuid_remove_payrun_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tds',
            name='uuid',
        ),
        migrations.RunSQL(
            sql=[
                'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";',
                'ALTER TABLE configs_component ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE configs_component ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE configs_component ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE configs_component ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE configs_tds ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE configs_tds ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE configs_tds ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE configs_tds ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
            ],
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='component',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='tds',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
