# Generated by Django 4.2.11 on 2026-05-22 05:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0004_bankdetailsack_bank_details'),
        ('payroll', '0004_form16entry_alter_payrun_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payees.payee'),
        ),
    ]
