# Generated by Django 4.2.11 on 2026-05-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payment_effective_from_payment_effective_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrecordregister',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
