# Generated by Django 4.2.11 on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrecordregister_account_number_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='form16',
            name='extraction_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
