# Generated by Django 4.2.11 on 2026-03-17 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrun_error_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='payrun',
            name='uuid',
        ),
        migrations.RunSQL(
            sql=[
                'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";',
                'DO $$\n'
                'DECLARE r record;\n'
                'BEGIN\n'
                '  FOR r IN\n'
                '    SELECT conname, conrelid::regclass AS tbl\n'
                '    FROM pg_constraint\n'
                '    WHERE contype = \'f\' AND conrelid::regclass::text IN (\'payroll_payment\', \'payroll_payrecordregister\', \'payroll_componentvalue\', \'payroll_form16entries\')\n'
                '  LOOP\n'
                '    EXECUTE format(\'ALTER TABLE %s DROP CONSTRAINT %I\', r.tbl, r.conname);\n'
                '  END LOOP;\n'
                'END $$;',
                'ALTER TABLE payroll_payment ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE payroll_payment ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE payroll_payment ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE payroll_payment ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE payroll_payrun ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE payroll_payrun ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE payroll_payrun ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE payroll_payrun ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE payroll_payrecordregister ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE payroll_payrecordregister ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE payroll_payrecordregister ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE payroll_payrecordregister ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE payroll_componentvalue ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE payroll_componentvalue ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE payroll_componentvalue ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE payroll_componentvalue ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE payroll_form16 ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE payroll_form16 ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE payroll_form16 ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE payroll_form16 ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
                'ALTER TABLE payroll_form16entries ALTER COLUMN id DROP IDENTITY IF EXISTS;',
                'ALTER TABLE payroll_form16entries ALTER COLUMN id DROP DEFAULT;',
                'ALTER TABLE payroll_form16entries ALTER COLUMN id TYPE uuid USING uuid_generate_v4();',
                'ALTER TABLE payroll_form16entries ALTER COLUMN id SET DEFAULT uuid_generate_v4();',
            ],
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='componentvalue',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='form16',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='form16entries',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='payment',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='payrecordregister',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='payrun',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
