# Generated by Django 4.2.11 on 2026-04-21 00:00

from django.db import migrations, models

def apply_constraints(apps, schema_editor):
    """
    Ensure PostgreSQL foreign key constraints expected by the historical
    models across multiple applications (payroll, payees, configs, core, zohopeople) exist.

    Earlier revisions of this migration path could leave PostgreSQL databases
    without some foreign key constraints after the UUID-to-integer rollback. This
    repair step is intentionally idempotent so fresh databases remain unaffected
    while older environments can be healed safely.
    """
    if schema_editor.connection.vendor != 'postgresql':
        return

    connection = schema_editor.connection
    target_apps = ['payroll', 'payees', 'configs', 'core', 'zohopeople']

    with connection.cursor() as cursor:
        for app_name in target_apps:
            app_config = apps.get_app_config(app_name)
            for model in app_config.get_models():
                if model._meta.proxy:
                    continue

                table_name = model._meta.db_table
                # Safety check: skip tables that don't exist yet (important for fresh migrations/downstream apps)
                cursor.execute(
                    "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = %s AND table_schema = current_schema())",
                    [table_name]
                )
                if not cursor.fetchone()[0]:
                    continue

                # Audit existing FKs with their delete rules
                cursor.execute("""
                    SELECT 
                        kcu.column_name, 
                        ccu.table_name AS target_table, 
                        ccu.column_name AS target_column,
                        rc.delete_rule,
                        tc.constraint_name
                    FROM information_schema.table_constraints AS tc
                    JOIN information_schema.key_column_usage AS kcu 
                        ON tc.constraint_name = kcu.constraint_name AND tc.constraint_schema = kcu.constraint_schema
                    JOIN information_schema.constraint_column_usage AS ccu 
                        ON tc.constraint_name = ccu.constraint_name AND tc.constraint_schema = ccu.constraint_schema
                    JOIN information_schema.referential_constraints AS rc 
                        ON tc.constraint_name = rc.constraint_name AND tc.constraint_schema = rc.constraint_schema
                    WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_name = %s AND tc.table_schema = current_schema()
                """, [table_name])
                existing_fks = {}
                for col, t_table, t_col, d_rule, c_name in cursor.fetchall():
                    existing_fks[col] = {
                        'target_table': t_table,
                        'target_column': t_col,
                        'delete_rule': d_rule,
                        'constraint_name': c_name
                    }

                for field in model._meta.local_fields:
                    remote_field = getattr(field, 'remote_field', None)
                    if remote_field is None or not getattr(field, 'db_constraint', True):
                        continue

                    target_table = field.target_field.model._meta.db_table
                    target_column = field.target_field.column
                    
                    # Safety check: skip if target table doesn't exist yet
                    cursor.execute(
                        "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = %s AND table_schema = current_schema())",
                        [target_table]
                    )
                    if not cursor.fetchone()[0]:
                        continue

                    # Expected behavior
                    on_delete_behavior = getattr(field.remote_field, "on_delete", None)
                    on_delete_sql = "CASCADE"
                    if on_delete_behavior == models.SET_NULL:
                        on_delete_sql = "SET NULL"
                    elif on_delete_behavior == models.PROTECT:
                        on_delete_sql = "RESTRICT"

                    existing = existing_fks.get(field.column)
                    
                    # If matches everything including the delete rule, we're good
                    if (existing and 
                        existing['target_table'] == target_table and 
                        existing['target_column'] == target_column and 
                        existing['delete_rule'] == on_delete_sql):
                        continue

                    # If it exists but is wrong, drop it first
                    if existing:
                        cursor.execute(f"ALTER TABLE {schema_editor.quote_name(table_name)} DROP CONSTRAINT {schema_editor.quote_name(existing['constraint_name'])}")

                    # Restore/Correct the constraint
                    quoted_table = schema_editor.quote_name(table_name)
                    quoted_target = schema_editor.quote_name(target_table)
                    quoted_column = schema_editor.quote_name(field.column)
                    quoted_target_col = schema_editor.quote_name(target_column)
                    
                    fk_orig_name = f"fk_{table_name}_{field.column}"[:63]
                    quoted_fk = schema_editor.quote_name(fk_orig_name)
                    
                    sql = (
                        f"ALTER TABLE {quoted_table} ADD CONSTRAINT {quoted_fk} "
                        f"FOREIGN KEY ({quoted_column}) REFERENCES {quoted_target} ({quoted_target_col}) "
                        f"ON DELETE {on_delete_sql} DEFERRABLE INITIALLY DEFERRED"
                    )

                    # Safety check: Ensure column types are compatible (both UUID or both NOT UUID)
                    cursor.execute(
                        "SELECT data_type FROM information_schema.columns WHERE table_name = %s AND column_name = %s "
                        "UNION ALL "
                        "SELECT data_type FROM information_schema.columns WHERE table_name = %s AND column_name = %s",
                        [table_name, field.column, target_table, target_column]
                    )
                    types = [r[0] for r in cursor.fetchall()]
                    if len(types) == 2:
                        source_type, target_type = types
                        is_source_uuid = 'uuid' in source_type.lower()
                        is_target_uuid = 'uuid' in target_type.lower()
                        if is_source_uuid != is_target_uuid:
                            print(f"Skipping FK {fk_orig_name}: incompatible types {source_type} -> {target_type}")
                            continue

                    schema_editor.execute(sql)
class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_remove_payment_uuid_remove_payrun_uuid_and_more'),
        ('configs', '0003_remove_tds_uuid_alter_component_id_alter_tds_id'),
        ('payees', '0006_remove_bankdetails_uuid_remove_payee_uuid_and_more'),
        ('core', '0007_alter_adminnotification_id_alter_document_id_and_more'),
        ('zohopeople', '0002_alter_zohopeopleformtoken_id'),
    ]

    operations = [
        migrations.RunPython(apply_constraints, reverse_code=migrations.RunPython.noop),
    ]
