# Generated by Django 4.2.11 on 2026-04-23 12:37

from django.db import migrations, models

def force_bigint_id(apps, schema_editor):
    """
    Unified implementation of the UUID-to-BigInt migration.
    NOTE: This logic is intentionally duplicated across several migration files 
    (payroll, core, payees, configs, zohopeople) to ensure migrations remain 
    strictly self-contained and stable across future codebase refactors.
    """
    if schema_editor.connection.vendor != 'postgresql':
        return
    
    tables = [
        'payroll_componentvalue', 'payroll_form16', 'payroll_form16entries',
        'payroll_payment', 'payroll_payrecordregister', 'payroll_payrun'
    ]

    with schema_editor.connection.cursor() as cursor:
        for table in tables:
            cursor.execute(
                "SELECT data_type FROM information_schema.columns "
                "WHERE table_name = %s AND column_name = 'id'",
                [table]
            )
            row = cursor.fetchone()
            if not row:
                continue
                
            current_type = row[0]
            quoted_table = schema_editor.quote_name(table)
            quoted_id_col = schema_editor.quote_name('id')
            
            if current_type == 'uuid':
                old_id_col_name = "id_old_uuid"
                quoted_old_id_col = schema_editor.quote_name(old_id_col_name)
                
                # 1. Capture referencing FKs BEFORE dropping PK CASCADE
                # Strict isolation: only capture dependencies referencing the ID primary key
                cursor.execute("""
                    SELECT 
                        tc.table_name, 
                        kcu.column_name,
                        rc.delete_rule,
                        rc.update_rule,
                        tc.constraint_name
                    FROM information_schema.table_constraints AS tc
                    JOIN information_schema.key_column_usage AS kcu 
                        ON tc.constraint_name = kcu.constraint_name 
                        AND tc.constraint_schema = kcu.constraint_schema
                    JOIN information_schema.constraint_column_usage AS ccu 
                        ON tc.constraint_name = ccu.constraint_name 
                        AND tc.constraint_schema = ccu.constraint_schema
                    JOIN information_schema.referential_constraints AS rc 
                        ON tc.constraint_name = rc.constraint_name 
                        AND tc.constraint_schema = rc.constraint_schema
                    WHERE tc.constraint_type = 'FOREIGN KEY' 
                      AND ccu.table_name = %s 
                      AND ccu.column_name = 'id'
                      AND tc.table_schema = current_schema();
                """, [table])
                referencing_fks = cursor.fetchall()
        
                # 2. Rename and Drop PK
                cursor.execute(f"ALTER TABLE {quoted_table} RENAME COLUMN {quoted_id_col} TO {quoted_old_id_col}")
                cursor.execute(
                    "SELECT conname FROM pg_constraint c "
                    "JOIN pg_class col ON col.oid = c.conrelid "
                    "WHERE col.relname = %s AND c.contype = 'p'",
                    [table]
                )
                pk_row = cursor.fetchone()
                if pk_row:
                    pk_name = schema_editor.quote_name(pk_row[0])
                    cursor.execute(f"ALTER TABLE {quoted_table} DROP CONSTRAINT {pk_name} CASCADE")
                
                # 3. Add new BigInt identity
                cursor.execute(f"ALTER TABLE {quoted_table} ADD COLUMN {quoted_id_col} bigint GENERATED BY DEFAULT AS IDENTITY")
                cursor.execute(
                    f"UPDATE {quoted_table} SET {quoted_id_col} = sub.new_id "
                    f"FROM (SELECT {quoted_old_id_col}, row_number() OVER (ORDER BY {quoted_old_id_col}) as new_id FROM {quoted_table}) sub "
                    f"WHERE {quoted_table}.{quoted_old_id_col} = sub.{quoted_old_id_col}"
                )
                cursor.execute(f"ALTER TABLE {quoted_table} ADD PRIMARY KEY ({quoted_id_col})")
                
                # 4. Advance Sequence
                cursor.execute(f"SELECT max({quoted_id_col}) FROM {quoted_table}")
                max_id = cursor.fetchone()[0]
                cursor.execute(
                    "SELECT setval(pg_get_serial_sequence(%s, 'id'), %s, %s)",
                    [table, max_id or 1, max_id is not None]
                )
        
                # 5. Handle Children
                for ref_table, ref_column, delete_rule, update_rule, _ in referencing_fks:
                    quoted_ref_table = schema_editor.quote_name(ref_table)
                    quoted_ref_col = schema_editor.quote_name(ref_column)
                    tmp_ref_col = schema_editor.quote_name(f"{ref_column}_new_bigint")
        
                    # Property Introspection
                    cursor.execute(
                        "SELECT is_nullable, column_default FROM information_schema.columns "
                        "WHERE table_name = %s AND column_name = %s",
                        [ref_table, ref_column]
                    )
                    row = cursor.fetchone()
                    is_nullable = row[0] == 'YES'
                    col_default = row[1]
                    
                    # Uniqueness Introspection
                    cursor.execute("""
                        SELECT EXISTS (
                            SELECT 1 FROM pg_index idx
                            JOIN pg_class t ON t.oid = idx.indrelid
                            JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(idx.indkey)
                            WHERE t.relname = %s AND a.attname = %s AND idx.indisunique AND idx.indnkeyatts = 1
                        )
                    """, [ref_table, ref_column])
                    is_unique = cursor.fetchone()[0]
        
                    cursor.execute("""
                        SELECT conname, pg_get_constraintdef(c.oid), 'constraint'
                        FROM pg_constraint c
                        JOIN pg_class t ON t.oid = c.conrelid
                        WHERE t.relname = %s AND c.contype = 'u' 
                          AND c.conkey @> (SELECT array_agg(attnum) FROM pg_attribute WHERE attrelid = t.oid AND attname = %s)
                        UNION ALL
                        SELECT i.relname, pg_get_indexdef(idx.indexrelid), 'index'
                        FROM pg_index idx
                        JOIN pg_class t ON t.oid = idx.indrelid
                        JOIN pg_class i ON i.oid = idx.indexrelid
                        JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(idx.indkey)
                        WHERE t.relname = %s AND a.attname = %s AND idx.indisunique AND idx.indnkeyatts > 1
                    """, [ref_table, ref_column, ref_table, ref_column])
                    composite_definitions = cursor.fetchall()
        
                    # Swap Data
                    cursor.execute(f"ALTER TABLE {quoted_ref_table} ADD COLUMN IF NOT EXISTS {tmp_ref_col} bigint")
                    cursor.execute(
                        f"UPDATE {quoted_ref_table} SET {tmp_ref_col} = parent.{quoted_id_col} "
                        f"FROM (SELECT {quoted_id_col}, {quoted_old_id_col} FROM {quoted_table}) parent WHERE {quoted_ref_table}.{quoted_ref_col} = parent.{quoted_old_id_col}"
                    )
                    cursor.execute(f"ALTER TABLE {quoted_ref_table} DROP COLUMN {quoted_ref_col} CASCADE")
                    cursor.execute(f"ALTER TABLE {quoted_ref_table} RENAME COLUMN {tmp_ref_col} TO {quoted_ref_col}")
        
                    # Restore Attributes
                    if not is_nullable:
                        cursor.execute(f"ALTER TABLE {quoted_ref_table} ALTER COLUMN {quoted_ref_col} SET NOT NULL")
                    if col_default:
                        cursor.execute(f"ALTER TABLE {quoted_ref_table} ALTER COLUMN {quoted_ref_col} SET DEFAULT {col_default}")
                    
                    for name, definition, def_type in composite_definitions:
                        if def_type == 'constraint':
                            cursor.execute(f"ALTER TABLE {quoted_ref_table} ADD CONSTRAINT {schema_editor.quote_name(name)} {definition}")
                        else:
                            cursor.execute("SELECT to_regclass(%s)", [name])
                            if cursor.fetchone()[0] is None:
                                cursor.execute(definition)
        
                    # Restore FK
                    fk_name = schema_editor.quote_name(f"fk_{ref_table}_{ref_column}"[:63])
                    cursor.execute(
                        f"ALTER TABLE {quoted_ref_table} ADD CONSTRAINT {fk_name} "
                        f"FOREIGN KEY ({quoted_ref_col}) REFERENCES {quoted_table} ({quoted_id_col}) "
                        f"ON DELETE {delete_rule} ON UPDATE {update_rule} DEFERRABLE INITIALLY DEFERRED"
                    )
        
                    # Audit and Restore Index if missing
                    cursor.execute("""
                        SELECT EXISTS (
                            SELECT 1 FROM pg_index idx
                            JOIN pg_class t ON t.oid = idx.indrelid
                            JOIN pg_attribute a ON a.attrelid = t.oid
                            WHERE t.relname = %s 
                              AND a.attname = %s 
                              AND idx.indisvalid 
                              AND idx.indislive 
                              AND a.attnum = ANY(idx.indkey)
                        )
                    """, [ref_table, ref_column])
                    if not cursor.fetchone()[0]:
                        idx_name = schema_editor.quote_name(f"idx_{ref_table}_{ref_column}"[:63])
                        if is_unique:
                            cursor.execute(f"CREATE UNIQUE INDEX IF NOT EXISTS {idx_name} ON {quoted_ref_table} ({quoted_ref_col})")
                        else:
                            cursor.execute(f"CREATE INDEX IF NOT EXISTS {idx_name} ON {quoted_ref_table} ({quoted_ref_col})")
        
                cursor.execute(f"ALTER TABLE {quoted_table} DROP COLUMN {quoted_old_id_col}")
            else:
                from django.db import ProgrammingError
                # Standardization Path
                cursor.execute(
                    "SELECT count(*) FROM pg_attribute a JOIN pg_class t ON t.oid = a.attrelid "
                    "WHERE t.relname = %s AND a.attname = 'id' AND a.attidentity != ''",
                    [table]
                )
                if cursor.fetchone()[0] == 0:
                    cursor.execute(f"ALTER TABLE {quoted_table} ALTER COLUMN {quoted_id_col} DROP DEFAULT")
                    try:
                        cursor.execute(f"ALTER TABLE {quoted_table} ALTER COLUMN {quoted_id_col} ADD GENERATED BY DEFAULT AS IDENTITY")
                    except ProgrammingError as e:
                        if 'already an identity column' not in str(e).lower():
                            raise
                
                cursor.execute(
                    f"SELECT setval(pg_get_serial_sequence(%s, 'id'), coalesce(max({quoted_id_col}), 0) + 1, false) FROM {quoted_table}",
                    [table]
                )

class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_restore_constraints'),
        ('configs', '0004_alter_component_id_alter_tds_id'),
        ('payees', '0007_alter_bankdetails_id_alter_bankdetailsack_id_and_more'),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(force_bigint_id, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='componentvalue',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='form16',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='form16entries',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='payment',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='payrecordregister',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='payrun',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
    ]
