# Generated by Django 4.2.11 on 2026-04-30 00:00

from django.db import migrations, models

def repair_fk_on_delete_rules(apps_registry, target_apps, connection, lock_timeout='20s', strict=False):
    """
    Self-contained helper to audit and repair PostgreSQL foreign key ON DELETE rules.
    NOTE: This logic is inlined to ensure migrations remain strictly self-contained.
    """
    from django.db.utils import OperationalError
    import logging
    logger = logging.getLogger(__name__)

    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        cursor.execute("SHOW lock_timeout")
        old_timeout = cursor.fetchone()[0]
        skipped_fks = []
        unvalidated_fks = []
        repaired_count = 0        
        try:
            cursor.execute("SET lock_timeout = %s", [lock_timeout])
            cursor.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = current_schema()")
            existing_tables = {row[0] for row in cursor.fetchall()}

            for app_name in target_apps:
                try:
                    app_config = apps_registry.get_app_config(app_name)
                except LookupError:
                    continue
                    
                for model in app_config.get_models():
                    if model._meta.proxy:
                        continue

                    table_name = model._meta.db_table
                    if table_name not in existing_tables:
                        continue

                    cursor.execute("""
                        SELECT kcu.column_name, rc.delete_rule, tc.constraint_name, rc.update_rule,
                               tc.is_deferrable, tc.initially_deferred
                        FROM information_schema.table_constraints AS tc
                        JOIN information_schema.key_column_usage AS kcu 
                            ON tc.constraint_name = kcu.constraint_name AND tc.constraint_schema = kcu.constraint_schema
                        JOIN information_schema.referential_constraints AS rc 
                            ON tc.constraint_name = rc.constraint_name AND tc.constraint_schema = rc.constraint_schema
                        WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_name = %s AND tc.table_schema = current_schema()
                    """, [table_name])
                    existing_fks = {row[0]: row[1:] for row in cursor.fetchall()}
                    
                    for field in model._meta.local_fields:
                        if not getattr(field, 'remote_field', None) or not getattr(field, 'db_constraint', True):
                            continue

                        on_delete_behavior = getattr(field.remote_field, "on_delete", None)
                        expected = "NO ACTION"
                        if on_delete_behavior == models.SET_NULL:
                            expected = "SET NULL"
                        elif on_delete_behavior == models.CASCADE:
                            expected = "CASCADE"
                        elif on_delete_behavior == models.SET_DEFAULT:
                            expected = "SET DEFAULT"
                        elif on_delete_behavior == models.PROTECT or (hasattr(models, 'RESTRICT') and on_delete_behavior == models.RESTRICT):
                            expected = "RESTRICT"

                        if field.column not in existing_fks:
                            continue
                        d_rule, c_name, u_rule, is_def, init_def = existing_fks[field.column]
                        if d_rule == expected:
                            continue

                        target_table = field.target_field.model._meta.db_table
                        target_column = field.target_field.column
                        if target_table not in existing_tables:
                            continue

                        defer = f" DEFERRABLE INITIALLY {'DEFERRED' if init_def == 'YES' else 'IMMEDIATE'}" if is_def == 'YES' else ""
                        sql = (
                            f"ALTER TABLE {connection.ops.quote_name(table_name)} "
                            f"DROP CONSTRAINT {connection.ops.quote_name(c_name)}, "
                            f"ADD CONSTRAINT {connection.ops.quote_name(c_name)} "
                            f"FOREIGN KEY ({connection.ops.quote_name(field.column)}) "
                            f"REFERENCES {connection.ops.quote_name(target_table)} ({connection.ops.quote_name(target_column)}) "
                            f"ON DELETE {expected} ON UPDATE {u_rule}{defer} NOT VALID"
                        )
                        try:
                            cursor.execute(sql)
                            try:
                                cursor.execute(f"ALTER TABLE {connection.ops.quote_name(table_name)} VALIDATE CONSTRAINT {connection.ops.quote_name(c_name)}")
                            except OperationalError as val_e:
                                if getattr(val_e, 'pgcode', None) == '55P03' or 'lock timeout' in str(val_e).lower():
                                    unvalidated_fks.append(f"{table_name}.{field.column}")
                                    logger.warning("Skipped validation for %s.%s due to lock timeout.", table_name, field.column)
                                else:
                                    raise
                            repaired_count += 1
                        except OperationalError as e:
                            if getattr(e, 'pgcode', None) == '55P03' or 'lock timeout' in str(e).lower():
                                skipped_fks.append(f"{table_name}.{field.column}")
                                logger.warning("Skipped FK repair for %s.%s due to lock timeout.", table_name, field.column)
                                continue
                            raise
        finally:
            cursor.execute("SET lock_timeout = %s", [old_timeout])
        
        if skipped_fks or unvalidated_fks:
            if skipped_fks:
                logger.warning(
                    "Skipped repairing %s foreign key constraint(s) due to lock timeouts after repairing %s: %s",
                    len(skipped_fks),
                    repaired_count,
                    ", ".join(skipped_fks)
                )
            if unvalidated_fks:
                logger.warning(
                    "Repaired but failed to validate %s foreign key constraint(s) due to lock timeouts after repairing %s: %s",
                    len(unvalidated_fks),
                    repaired_count,
                    ", ".join(unvalidated_fks)
                )
            
            if not strict:
                import sys
                import os
                current_settings = os.environ.get('DJANGO_SETTINGS_MODULE', 'youpayroll.settings.base')
                
                msg = f"\n\n==================== WARNING ====================\nMigration completed, but "
                if skipped_fks:
                    msg += f"{len(skipped_fks)} constraint(s) were skipped due to lock timeouts. "
                if unvalidated_fks:
                    msg += f"{len(unvalidated_fks)} constraint(s) were left NOT VALID due to validation lock timeouts. "
                
                msg += (
                    f"\nPlease run the following command during a maintenance window to complete the schema update:\n"
                    f"DJANGO_SETTINGS_MODULE={current_settings} python manage.py repair_fk_constraints --lock-timeout 60000ms\n"
                    f"=================================================\n\n"
                )
                sys.stderr.write(msg)

        if strict and (skipped_fks or unvalidated_fks):
            raise RuntimeError(
                f"Repaired {repaired_count} FKs, skipped {len(skipped_fks)}, unvalidated {len(unvalidated_fks)} due to lock timeouts."
            )

def standardize_delete_rules(apps, schema_editor):
    """
    Standardize PostgreSQL foreign key ON DELETE rules across target apps.
    This logic is self-contained to ensure historical stability.
    """
    repair_fk_on_delete_rules(
        apps_registry=apps, 
        target_apps=['payroll', 'payees', 'configs', 'core', 'zohopeople'],
        connection=schema_editor.connection,
        lock_timeout='20s', 
        strict=False
    )

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('payroll', '0010_force_bigint_id'),
        ('configs', '0004_alter_component_id_alter_tds_id'),
        ('payees', '0007_alter_bankdetails_id_alter_bankdetailsack_id_and_more'),
        ('core', '0008_alter_adminnotification_id_alter_document_id_and_more'),
        ('zohopeople', '0003_alter_zohopeopleformtoken_id'),
    ]

    operations = [
        migrations.RunPython(standardize_delete_rules, reverse_code=migrations.RunPython.noop),
    ]
